### PR TITLE
Try the Github theme

### PR DESCRIPTION
**Pull request by yihui**
Hold on. Do not merge it unless you are happy with the theme.

### CODE REVIEW

**Comment by jtleek** [comment]
How do we preview it

**Comment by yihui** [comment]
Right now you see an orange dot on my commit and the status under the PR says "Some checks haven’t completed yet":

image

This means Netlify is still building and deploying the preview. Wait for it to complete, and you will see the orange dot change to a green checkmark. That is when you will be able to preview the site.

**Comment by yihui** [comment]
Build complete. (Normally it won't take this long)

Now you need to find a post that contains code to see the style, e.g. https://deploy-preview-4--simplystats.netlify.com/2016/08/26/googlesheets/

**Comment by yihui** [comment]
If you are happy with it, click the Merge pull request button. I found that you didn't seem to have used the merge button last time in #3.

**Comment by jtleek** [comment]
Thanks this is great!

**Pull request merged**
